packages:
  - 'modules/bootstrap'
  - 'modules/infrastructure'
  - 'modules/rmu'
  - 'modules/command/*'
  - 'modules/query/*'

catalog:
  # Runtime dependencies
  fp-ts: ^2.16.2
  ulidx: ^2.3.0
  tslog: ^4.9.2
  event-store-adapter-js: 2.2.163-snapshot.8
  moment: ^2.29.4
  '@aws-sdk/client-dynamodb': ^3.413.0
  '@aws-sdk/client-dynamodb-streams': ^3.413.0
  'aws-sdk': ^2.1459.0
  'aws-lambda': ^1.0.7
  graphql: ^16.8.1
  'graphql-fields': ^2.0.3
  'graphql-scalars': ^1.22.4
  tslib: ^2.6.2
  'type-graphql': 2.0.0-rc.2
  '@prisma/client': ^6.0.0
  '@apollo/server': ^4.12.2
  'reflect-metadata': ^0.2.0
  yargs: ^17.7.0

  # Dev dependencies
  '@biomejs/biome': 1.9.4
  '@types/aws-lambda': ^8.10.0
  '@types/jest': ^29.5.5
  '@types/node': ^22.0.0
  '@types/winston': ^2.4.4
  '@types/yargs': ^17.0.0
  '@types/graphql-fields': ^1.3.9
  '@typescript-eslint/eslint-plugin': ^8.0.0
  '@typescript-eslint/parser': ^8.0.0
  jest: ^29.7.0
  rimraf: ^6.0.0
  testcontainers: ^10.2.1
  ts-jest: ^29.1.1
  ts-node: ^10.9.1
  typescript: ^5.2.2
  prisma: ^6.0.0
  'typegraphql-prisma': ^0.28.0
